## Numpy Array operations

In [2]:
import numpy as np

In [10]:
arr = np.arange(11)
print("Normal Array: ",arr)
print("Basic slicing \n",arr[2:7])
print("With step",arr[1:8:2])
print("Negative indexing", arr[-3])


Normal Array:  [ 0  1  2  3  4  5  6  7  8  9 10]
Basic slicing 
 [2 3 4 5 6]
With step [1 3 5 7]
Negative indexing 8


In [13]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element ",arr_2d[1, 2])
print("Entire Row: ",arr_2d[1])
print("Entire Colunm: ", arr_2d[:, 1])

Specific element  6
Entire Row:  [4 5 6]
Entire Colunm:  [2 5 8]


### Sorting

In [ ]:
unsorted = np.array([3, 5, 2, 9, 1, 6, 8, 4, 7])
print("Sorted array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column: \n", np.sort(arr_2d_unsorted, axis=0))


Sorted array:  [1 2 3 4 5 6 7 8 9]
Sorted 2D array by column: 
 [[1 1]
 [2 2]
 [3 3]]


### Filter

In [22]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even Numbers: ", even_number)

Even Numbers:  [ 2  4  6  8 10]


### Filter with mask

In [24]:
mask = numbers > 5
print("Numbers greater than 5: ",numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [27]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP Where: ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where:  [ 6  7  8  9 10]


In [30]:
condition_array = np.where(numbers > 5, numbers*2,numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]
