## Numpy array and basics
Learn about numpy

In [4]:
import numpy as np

### Creating array from list

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array : ", arr_1d)

arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
print("2D array: ",arr_2d) 

1D array :  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [8]:
py_list = [1, 2, 3]
print("python list multiplication", py_list * 2)

np_array = np.array([1, 2, 3]) # element wise multiplication 
print("python array multiplication", np_array * 2)

import time

start = time.time()

py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ",time.time()-start)

start = time.time()
np_array = np.arange(1000000)*2

print("\n Numpy operation time: ",time.time()-start)


python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]

 List operation time:  0.03403902053833008

 Numpy operation time:  0.002492189407348633


### Creating array from scratch


In [ ]:
zeros = np.zeros((3, 4))

print("Zeros array: \n", zeros)

one = np.ones((2, 3))

print("One array: \n ",one)

full = np.full((2,2),7)

print("Full array: \n ",full)

random = np.random.random((2 ,3))

print("Random array: ",random)

sequence = np.arange(0, 10, 2)

print("Sequence array: ",sequence)



Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One array: 
  [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
  [[7 7]
 [7 7]]
Random array:  [[0.62468936 0.57041575 0.52808164]
 [0.63452178 0.02775707 0.44121765]]
Sequence array:  [0 2 4 6 8]


### Vector, Matrix and Tensor

In [23]:
vector = np.array([1, 2, 3])
print("Vector: ",vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Matrix : ",matrix)

tensor = np.array([[[1, 2],[3, 4]],
                   [[5, 6],[7, 8]]])

print("Tensor: ",tensor)

Vector:  [1 2 3]
Matrix :  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [28]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ",arr.ndim)
print("Size ", arr.size)
print("Dtype ",arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
Dtype  int64


### Array Reshaping

In [38]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped array \n", reshaped)

flattened = reshaped.flatten()
print("Flattened array: \n",flattened)

# ravel (return view, instead of copy)
raveled = reshaped.ravel()
print("Raveled \n",raveled) 

# Transpose Matrix

transpose = reshaped.T
print("Transpose array \n", transpose)




Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
